package org.fkjava.cxf.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2018-06-20T17:38:08.583+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://ws.cxf.fkjava.org/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "getAllCats", targetNamespace = "http://ws.cxf.fkjava.org/", className = "org.fkjava.cxf.ws.GetAllCats")
    @WebMethod
    @ResponseWrapper(localName = "getAllCatsResponse", targetNamespace = "http://ws.cxf.fkjava.org/", className = "org.fkjava.cxf.ws.GetAllCatsResponse")
    public org.fkjava.cxf.ws.GetAllCatsResponse.Return getAllCats();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://ws.cxf.fkjava.org/", className = "org.fkjava.cxf.ws.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://ws.cxf.fkjava.org/", className = "org.fkjava.cxf.ws.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCatsByUser", targetNamespace = "http://ws.cxf.fkjava.org/", className = "org.fkjava.cxf.ws.GetCatsByUser")
    @WebMethod
    @ResponseWrapper(localName = "getCatsByUserResponse", targetNamespace = "http://ws.cxf.fkjava.org/", className = "org.fkjava.cxf.ws.GetCatsByUserResponse")
    public java.util.List<org.fkjava.cxf.ws.Cat> getCatsByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        org.fkjava.cxf.ws.User arg0
    );
}
